apiVersion: v1
kind: PersistentVolume
metadata:
  name: counter-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/counter-data
    type: DirectoryOrCreate
